kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: experiment1
  namespace: chaos-testing
#  annotations:
#    experiment.chaos-mesh.org/pause: 'false'
spec:
  schedule: '@every 15s'
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - squidgame
      labelSelectors:
        app: myapp
    mode: one
    action: pod-kill
    duration: 5m
    gracePeriod: 0
